conf:
    rabbit:
        host: rabbitmq
        port: 5672
        user: ${RABBIT_USER}
        pass: ${RABBIT_PASS}

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_OFX_REALM}

eureka:
    client:
        service-url:
            defaultZone : http://ofx-service-registry:8761/eureka/